[package]
name = "ink_utils"
version.workspace = true
authors.workspace = true
edition.workspace = true

license.workspace = true
readme = "README.md"
repository.workspace = true
documentation = "https://docs.rs/ink_utils"
homepage.workspace = true
description = "Utilities used internally in ink_linting crates"
keywords.workspace = true
include = ["Cargo.toml", "*.rs", "LICENSE"]

[dependencies]
if_chain = "1.0.2"
parity_clippy_utils = "0.1.73"

[package.metadata.rust-analyzer]
rustc_private = true
